module.exports = {// Start Starter
  starter: {
    id: {
      type: 'INTEGER', primaryKey: true, autoIncrement: true,
      rules: { insertAble: false, updateAble: false, showAble: true },
    },
    application_id: { type: 'INTEGER', allowNull: false, defaultValue: 0,
      rules: { insertAble: true, updateAble: true },
    },
    is_active: { type: 'BOOLEAN', defaultValue: true, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    created_at: { type: 'DATETIME',
      defaultValue: 'NOW',
      rules: { insertAble: true, updateAble: false, showAble: true },
    },
    created_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: false, showAble: true },
    },
    updated_at: { type: 'DATETIME',
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    updated_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    deleted_at: { type: 'DATETIME',
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    deleted_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
  },

  test_user: {
    id: {
      type: 'INTEGER', primaryKey: true, autoIncrement: true,
      rules: { insertAble: false, updateAble: false, showAble: true },
    },
    application_id: { type: 'INTEGER', allowNull: false, defaultValue: 0,
      rules: { insertAble: true, updateAble: true },
    },
    username: { type: 'STRING', allowNull: false, unique: true, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    password: { type: 'STRING', allowNull: false, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    role: { type: 'STRING', allowNull: false, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    is_active: { type: 'BOOLEAN', defaultValue: true, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    created_at: { type: 'DATETIME',
      defaultValue: 'NOW',
      rules: { insertAble: true, updateAble: false, showAble: true },
    },
    created_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: false, showAble: true },
    },
    updated_at: { type: 'DATETIME',
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    updated_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    deleted_at: { type: 'DATETIME',
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
    deleted_by: { type: 'INTEGER', defaultValue: 0, 
      rules: { insertAble: true, updateAble: true, showAble: true },
    },
  },

};
