version: '3'
services:
  api:
    image: gtidocker7/api-frontendtest-dev:v1
    container_name: api-frontendtest-dev
    build: .
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: api.frontendtest.dev.griyatekno.id
      LETSENCRYPT_HOST: api.frontendtest.dev.griyatekno.id

networks:
    default:
        external:
            name: nginx-proxy
